spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_test_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  batch:
    job:
      enabled: false #disabled job run at startup
    jdbc:
      initialize-schema: ALWAYS
#-----APIs------------------------------------------------------
user-notification-url: http://localhost:8080/notification
